language: go
go:
  - 1.7.3
  - tip
install:
  - go get github.com/Masterminds/glide
  - go get github.com/golang/lint/golint
before_script:
script:
  - glide install
  - go build .
  - go test $(glide novendor)
  - go vet .
  - golint .
